### ISSUE TITLE
template-strings append function

### ISSUE THREAD

**Issue by dan-2019** [leafac/sqlite#3]
I'm trying to migrate from sqlite3 / sql-template-strings to @leafac/sqlite

I'm receiving an error that the append function does not exist
Is there an equivalent of sql-template-strings's append function ?
(https://www.npmjs.com/package/sql-template-strings#building-complex-queries-with-append)
If not, can you please consider adding it?

**Comment by leafac** [comment]
Hi @dan-2019,

Thanks for reaching out.

You’re right that @leafac/sqlite doesn’t support `.append()`, but I don’t think @leafac/sqlite needs `.append()`, given that @leafac/sqlite has raw SQL interpolation with `$${...}`.

To use the example from the section of `sql-template-strings`’s documentation that you linked:

```javascript
const query = SQL`SELECT * FROM books`
if (params.name) {
  query.append(SQL` WHERE name = ${params.name}`)
}
query.append(SQL` LIMIT 10 OFFSET ${params.offset || 0}`)
```

Could be written in @leafac/sqlite using raw SQL interpolation `$${...}`, for example:

```javascript
const query = sql`
  SELECT * FROM books
  $${params.name ? sql`WHERE name = ${params.name}` : sql``}
  LIMIT 10 OFFSET ${params.offset || 0}
`;
```

If you think that there’s something more to this, please reopen the issue.

Thanks.

**Comment by dan-2019** [comment]
My use case is that query building is spread over different functions with each potentially extending the query. How do I achieve this with row SQL interpolation without refactoring the code to build the query in one place?

Differently put, can raw SQL interpolation be used when two distinct building statements are needed?

**Comment by leafac** [comment]
@dan-2019

I suppose you can do something like:

```javascript
const extendedQuery = sql`
  $${originalQuery}
  WHERE name = ${params.name}
`;
```

Note how this amounts to appending new SQL.

There’s one detail to keep in mind: it appears that sql-template-strings’s `.append()` mutates the original query object, while the method I describe creates a new extended query.

I’d argue that in most cases the latter is preferable (in case you aren’t familiar with the concept, look up the advantages of “immutability”). But in some situations mutation makes more sense, particularly if already have an existing system that you’re trying to move to @leafac/sqlite.

In that case, you can do something like:

```javascript
function example(query) {
  query.sql = sql`
    $${query.sql}
    WHERE name = ${params.name}
  `;
}

const query = {
  sql: sql`
    SELECT ...
  `
};

example(query);
```

Note that extending a query is still creating a new object (it’s still immutable). But we wrapped the thing in our own object with a `.sql` field that we we mutate.

**Comment by dan-2019** [comment]
Thank you for the detail explanation! It certainly offers a workable solution.

That said, IMHO .append still looks more intuitive and easy to read, which was one of the major reasons I adopted the template string syntax in the first place.

**Comment by leafac** [comment]
> @dan-2019 
>
> Thank you for the detail explanation! It certainly offers a workable solution.

Great 😁

> That said, IMHO .append still looks more intuitive and easy to read, which was one of the major reasons I adopted the template string syntax in the first place.

Point taken. I’m hesitant to introduce mutable queries like that, but I’ll keep the idea on the back burner.
