### ISSUE TITLE
Updating the README.md file with the new imports.

### ISSUE THREAD

**Issue by FairyPenguin** [leafac/sqlite#5]
Hey Leandro, 

hope you are doing well.

Thanks for the effort and the great library.

Can you please update the examples and the new imports? 

I was using the library today and got the error 

```
"import { sql, Database } from "@leafac/sqlite";
         ^^^
SyntaxError: The requested module '@leafac/sqlite' does not provide an export named 'sql'"
```

and tried to figure out the problem until I discovered it in the changelog, which is hard to find at first sight.

**Comment by FairyPenguin** [comment]
For anyone facing the error of 

```
import { sql, Database } from "@leafac/sqlite";
         ^^^
SyntaxError: The requested module '@leafac/sqlite' does not provide an export named 'sql'
```

you need to update the import statement 

from:
> import { sql, Database } from "@leafac/sqlite";

to:
> import sql, { Database } from "@leafac/sqlite";

**Comment by leafac** [comment]
Thanks for catching that! And thanks for the nice words about the library 🤗

I’m in the process of moving this library under the [Radically Straightforward](https://github.com/radically-straightforward/radically-straightforward) umbrella, and I’ll address this as part of improving the documentation in general!
